api: <Bearer API Token>
rules:
  <Rule name>:
    mode: <or/and>
    field: <Check field>
    action: <block/challenge/js_challenge/allow/log/bypass/rewrite>
    target:
      - <Zone ID>
      - <Zone ID>
    entries:
      - <Contains check>
      - <Contains check>
  [more rules...]